version: "3.8"

services:
  php_fpm:
      build: .
      container_name: symfony_api_php_fpm
      restart: always
      working_dir: /usr/share/nginx/symfony-api
      volumes:
          - ./:/usr/share/nginx/symfony-api
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
